agourlay/cornichon

- src/main/scala/com/github/agourlay/cornichon/http/HttpDsl.scala
- src/main/scala/com/github/agourlay/cornichon/http/HttpEffects.scala
Add helper to query GQL endpoints, ```query``` is  Sangria doc, so the sangria macro must be used.
This could be used like
```scala
When I query_gql("url").withQuery(
graphql"""
query MyQuery {
channels {
results {
key
roles
}
}
}
"""
)
```
@OlegIlyenko WDYT about a helper like this in cornichon ?
> add helper to query GQL

- src/main/scala/com/github/agourlay/cornichon/core/Errors.scala
- src/main/scala/com/github/agourlay/cornichon/dsl/DataTable.scala
- src/main/scala/com/github/agourlay/cornichon/dsl/DslErrors.scala
- src/test/scala/com/github/agourlay/cornichon/dsl/DataTableSpec.scala
I noticed an issue in the parser: it was unable to handle unicode characters. `CharPredicate.Printable` and `CharPredicate.Visible` do not do the trick unfortunately. 
In this PR I treat JSON values generically (JSON parser takes care of them), but I implemented  a special parsing logic for header strings (since things like escaping need to be considered)
> Improved unicode character handling in databale parser

- src/main/scala/com/github/agourlay/cornichon/json/JsonSteps.scala
- src/main/scala/com/github/agourlay/cornichon/steps/regular/assertStep/StringAssertion.scala
- src/test/scala/com/github/agourlay/cornichon/examples/superHeroes/SuperHeroesScenario.scala
- src/test/scala/com/github/agourlay/cornichon/steps/regular/assertStep/StringAssertionSpec.scala
Hello @agourlay 
I have done a modest contribution on your test api library with the support of regexp;
```
Then assert body.path("name").regExpMatch(".*man".r)
```
let me know if you like it ^^
> Add RegExpAssertion support

- build.sbt
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/Engine.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/LogInstruction.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/ScenarioReport.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/feature/BaseFeature.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/http/server/HttpMockServerResource.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/http/server/MockServerRequestHandler.scala
- cornichon-experimental/src/main/scala/com/github/agourlay/cornichon/CornichonFeature.scala
- cornichon-experimental/src/main/scala/com/github/agourlay/cornichon/sbtinterface/CornichonFingerprint.scala
- cornichon-experimental/src/main/scala/com/github/agourlay/cornichon/sbtinterface/CornichonFramework.scala
- cornichon-experimental/src/main/scala/com/github/agourlay/cornichon/sbtinterface/CornichonRunner.scala
- cornichon-experimental/src/main/scala/com/github/agourlay/cornichon/sbtinterface/SbtCornichonReporter.scala
- cornichon-experimental/src/main/scala/com/github/agourlay/cornichon/sbtinterface/SbtCornichonTask.scala
- cornichon-experimental/src/test/scala/com/github/agourlay/cornichon/examples/DummyExamplesOne.scala
- cornichon-experimental/src/test/scala/com/github/agourlay/cornichon/examples/DummyExamplesThree.scala
- cornichon-experimental/src/test/scala/com/github/agourlay/cornichon/examples/DummyExamplesTwo.scala
- cornichon-scalatest/src/main/scala/com/github/agourlay/cornichon/scalatest/ScalatestFeature.scala
This cleans up the DSL scope from all the Scalatest leaked members
http://agourlay.github.io/cornichon/api/com/github/agourlay/cornichon/scalatest/ScalatestFeature.html
Removing those implicits should improve the compilation time a bit.
To use it one needs to add in the build.sbt
"com.github.agourlay" %% "cornichon-experimental" % "0.12.1-SNAPSHOT"
and
testFrameworks += new TestFramework("com.github.agourlay.cornichon.sbtinterface.CornichonFramework")
sbt testOnly *xxxx works out of the box to run a specific Feature.
There a couple a things missing to make it really usable:
- support testOnly at the scenario level like it is done with Scalatest
- ship a Teamcity reporter so that results are picked by the CI server
- maybe having a dedicated main runner like scalatest to run without sbt? …
> Introduce new experimental module without dependency to Scalatest

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/dsl/DataTable.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/json/CornichonJson.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/dsl/DataTableSpec.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/json/CornichonJsonSpec.scala
Improvements include:
* Empty cell value support
* Ability to get the raw cell values as a string (without parsing every cell value as a JSON)
Both of the features are very useful for custom parsers that use custom cell value validation and interpretation mechanism.
Here is an example of data table syntax that added by this PR:
```
| Name |   Age  | 2LettersName |
|      |        |    false     |
| Bob  |   11   |              |
```
> Data table improvements

- cornichon-benchmarks/src/main/scala/engine/EngineBench.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/Engine.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/RunState.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/steps/regular/ResourceStep.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/steps/regular/ResourceStepSpec.scala
- cornichon-docs/src/main/tut/custom-steps.md
Addresses Issue: https://github.com/agourlay/cornichon/issues/147
> The goal is to solve this issue of dangling test resources by introducing this kind of step.
> 
> ```
> case class ResourceStep(
>   resourceName: String,
>   createResource: EffectStep,
>   deleteResource: EffectStep) extends Step
> ```
> Once `createResource` is succesfully executed, `deletedResource` is assured to be executed as well as last step of the current scenario.
> 
> This similar to the semantic of a `finally` bloc.
Tests documenting the behaviour of ResourceStep [here](https://github.com/agourlay/cornichon/compare/master...rjsvaljean:add-resource-step#diff-b3cccf14319fd134bec38f6513acf285R1)
> Add ResourceStep to allow cleaning up acquired resources

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/Engine.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/Models.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/ScenarioExecutionContext.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/dsl/Dsl.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/feature/BaseFeature.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/core/EngineSpec.scala
- cornichon-experimental/src/main/scala/com/github/agourlay/cornichon/experimental/sbtinterface/SbtCornichonTask.scala
- cornichon-experimental/src/test/scala/com/github/agourlay/cornichon/experimental/examples/FocusedExperimentalScenario.scala
- cornichon-scalatest/src/main/scala/com/github/agourlay/cornichon/scalatest/ScalatestFeature.scala
- cornichon-scalatest/src/test/scala/com/github/agourlay/cornichon/examples/FocusedScenario.scala
Quite often I find myself in a situation where I'm working on a big feature and would like to quickly add new a scenario. As I'm working on it and have `sbt ~testOnly *FooFeature` in the background, it takes a lot of time to execute all existing scenarios including the new one which I'm working on.
This small addition makes it a bit easier to quickly pick a particular scenario and run it ignoring all other scenarios within a feature. Here is an example:
```scala
class FocusedScenario extends CornichonFeature {
def feature = Feature("feature/scenario focus") {
Scenario("Scenario 1") {
Given I wait(10 hours)
And I print_step("Scenario 1 is finished")
}
Scenario("My brand new scenario!").focused {
And I print_step("Scenario 2 is still WIP")
}
Scenario("Scenario 3") {
Given I wait(5 minutes) …
```
> Added ability to focus specific scenarios

- cornichon-http-mock/src/main/scala/com/github/agourlay/cornichon/http/server/MockServerRequestHandler.scala
- cornichon-http-mock/src/main/scala/com/github/agourlay/cornichon/http/server/MockServerResultsHolder.scala
- cornichon-http-mock/src/test/scala/com/github/agourlay/cornichon/http/MockServerExample.scala
This enhances the HttpMockServer so that it can send prepared responses, and the 400 status code.
For the example, I added some comments, but I'm not sure if that is something that you usually do. I've added them as scala comments, but I could also use `AttachAs` (or just remove them).
> Add 400 status and response bodies to HttpMockServer

- cornichon-http-mock/src/main/scala/com/github/agourlay/cornichon/http/server/MockHttpServer.scala
- cornichon-http-mock/src/test/scala/com/github/agourlay/cornichon/http/MockServerExample.scala
@cneijenhuis I pulled some of your work from https://github.com/agourlay/cornichon/compare/master...cneijenhuis:http-mock-port to check it myself :)
Adding the Task re-scheduling seems to do the trick. Let's see how it rolls on TravisCI.
> HttpMock tries its best to find an open port

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/json/JsonSteps.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/matchers/MatcherAssertion.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/matchers/MatcherResolver.scala
- cornichon-scalatest/src/test/scala/com/github/agourlay/cornichon/examples/superHeroes/SuperHeroesScenario.scala
Hi,
this adds `isNot` to the `JsonStepBuilder`, like: `Then assert body.path("name").isNot("Superman")` to explicitly not expect a specific json value.
I don't know if there is something like this already present. I just wanna make a suggestion here.
The PR also needs some polishing and probably more tests.
Please let me know what you think.
Matthias
> add isNot in JsonSteps

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/LogInstruction.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/package.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/steps/wrapped/EventuallyStep.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/steps/wrapped/EventuallyStepSpec.scala
This PR makes sure all distinct errors encountered during an `Eventually` run are logged properly.
The final error message remains unchanged by only mentioning the last error but the actual run log will provide all the details to hunt down the intermediary failures.
@cneijenhuis I hope this should be enough to prevent `people` from wasting hours chasing errors.
> eventuallyStep logs all distinct errors

- cornichon-docs/src/main/tut/modules/module-kafka.md
- cornichon-kafka/src/main/scala/com/github/agourlay/cornichon/kafka/KafkaDsl.scala
- cornichon-kafka/src/test/scala/com/github/agourlay/kafka/kafka/KafkaExample.scala
This PR reworks the Kafka DSL to enable users to work with dynamic configuration.
> kafka DSL creates one consumer/producer pair per feature

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/matchers/Matcher.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/matchers/MatchersSpec.scala
The "any-time", "any-date" & "any-date-time" matchers used the
`SimpleDateFormat` underneath, which is non-thread-safe for parsing due
to internal mutability. This caused errors in some cases when running
cornichon specs in a parallel way. E.g. the IntelliJ IDEA runner seems
to always run the specs serially, but SBT may run them in parallel,
causing the same set of specs to either succeed or fail depending on the
running environment.
Until Java 8 the common fix was to use a drop-in
replacement from Apache commons, `FastDateFormat`, implementing the same
`DateFormat` interface. But Java 8's java.time brought the newer,
immutable `DateTimeFormatter` class with default implementations for
most of the common temporal formats.
The added benefit is the less rigid checking against optional …
> Fix date/date-time/time matchers thread safety

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/http/QueryGQL.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/http/QueryGQLSpec.scala
When using the `withVariables` with variables of different types, like:
```
gql.withVariables(
"booleanVar" -> true,
"intVar" -> 42,
"stringVar" -> "hello"
)
```
the compiler tries to find one `Encoder` instance for all values, and fails to do so:
```
[error] /Users/yannsimon/projects/cornichon/cornichon-core/src/test/scala/com/github/agourlay/cornichon/http/QueryGQLSpec.scala:13:44: diverging implicit expansion for type io.circe.Encoder[A]
[error] starting with method encodeMapLike in object Encoder
[error]       val withVariables = gql.withVariables(
[error]                                            ^
```
This changes introduces `VarValue` to capture the suitable encoder for each element, instead of the whole map values.
The type class `Show`  does not seem to be used. I therefore have …
> can use different json encoders for each variable

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/RandomContext.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/RunState.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/ScenarioContext.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/ScenarioRunner.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/resolver/PlaceholderGenerator.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/resolver/PlaceholderResolver.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/resolver/PlaceholderResolverSpec.scala
- cornichon-docs/docs/placeholders.md
- cornichon-test-framework/src/test/scala/com/github/agourlay/cornichon/framework/examples/UniqueNumberScenario.scala
This PR adds supports for unique numbers generators at the scenario and global scope.
```scala
class UniqueNumberScenario extends CornichonFeature {
// running sequentially to get deterministic global assertions
override lazy val executeScenariosInParallel: Boolean = false
def feature = Feature("Example of unique number generation") {
Scenario("unique number scoped to Scenario") {
When I save("my-counter" -> "<scenario-unique-number>")
And I save("my-other-counter" -> "<scenario-unique-number>")
Then assert session_value("my-counter").is("1")
Then assert session_value("my-other-counter").is("2")
}
Scenario("unique number scoped globally (1)") {
When I save("my-counter" -> "<global-unique-number>")
Then assert session_value("my-counter").is("1")
}
Scenario("unique number scoped globally …
```
> introduce <scenario-unique-number> and <global-unique-number>

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/CornichonError.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/FeatureRunner.scala
- cornichon-test-framework/src/main/scala/com/github/agourlay/cornichon/framework/CornichonFeatureRunner.scala
This PR hardens the execution and reporting of `beforeFeature` & `afterFeature` to fix #383 
It tries it best to point at the exact problem and avoid uncaught issues which are difficult to debug.
> harden before/after feature hooks

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/Session.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/dsl/SessionSteps.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/json/JsonSteps.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/core/SessionProperties.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/json/JsonStepsSpec.scala
This is handy when comparing state after transition with `cornichon-check`.
For instance if you have saved a value twice in the `cutomer` key following an update transition.
```scala
And assert session_value("customer").asJson.path("version")
.compareWithPreviousValue[Int]{ case (prev, current) => GenericEqualityAssertion(prev + 1, current) }
``` 
Any type can be used as target as long as there is a `io.circe.Decoder` for it.
> JsonStepBuild can compare the previous and the current value

- benchmarks/src/main/scala/session/AddValuesBench.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/Session.scala
This function is core to the library and should execute as fast possible.
Cats.traverse is allocating quite a lot and we can easily do without.
> Optimize Session.addValues

- cornichon-http-mock/src/main/scala/com/github/agourlay/cornichon/http/server/MockHttpServer.scala
- cornichon-test-framework/src/test/scala/com/github/agourlay/cornichon/framework/examples/propertyCheck/stringReverse/ReverseAPI.scala
- cornichon-test-framework/src/test/scala/com/github/agourlay/cornichon/framework/examples/propertyCheck/turnstile/TurnstileAPI.scala
- cornichon-test-framework/src/test/scala/com/github/agourlay/cornichon/framework/examples/propertyCheck/webShop/WebShopAPI.scala
- cornichon-test-framework/src/test/scala/com/github/agourlay/cornichon/framework/examples/superHeroes/server/SuperHeroesHttpAPI.scala
The switche to nio2 was motivated by a noisy stacktrace with nio1
https://github.com/http4s/http4s/issues/2383
However nio2 is being deprecated in 0.22 and there is no replacement
https://github.com/http4s/http4s/issues/4572
As a result we switch back to nio1 and hope the stacktrace won't be too noisy
> Http4s servers use nio1 instead of nio2

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/json/CornichonJson.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/matchers/MatcherResolver.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/json/CornichonJsonProperties.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/json/CornichonJsonSpec.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/json/JsonStepsSpec.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/matchers/MatchersProperties.scala
Investigation for https://github.com/agourlay/cornichon/issues/676
In this PR the `MatcherResolver` does not assume anymore any particular ordering for the corresponding `JsonPath`.
Also `findAllPathWithValue` was greatly simplified, it should run much faster.
> Harden MatcherResolver

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/http/steps/HeadersSteps.scala
Compilation error with scala 2.12:
```
core/src/main/scala/com/github/agourlay/cornichon/http/steps/HeadersSteps.scala:22:56: value traverse is not a member of (String, String)*
```
Using a `List` instead works in scala 2.12 & scala 2.13
> fix scala 2.12 compilation

- build.sbt
- cornichon-docs/docs/installation.md
Since [0.19.7](https://github.com/agourlay/cornichon/releases/tag/v0.19.7) Java 11 is required at runtime due to the Caffeine library.
We might as well use more modern byte code when releasing.
> use Java 11 bytecode

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/dsl/CoreDsl.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/steps/wrapped/WithDataInputStep.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/steps/wrapped/WithDataInputStepSpec.scala
Hello!
I was trying to create a test like this (simplified for the example):
```
Scenario("Create a cart") {
WithDataInputs("""
| cart-cust |
| "cust1"   |
| null      |
""") {
When I post("/carts").withBody(s"""
{
"customerId": <cart-cust>
}
""")
Then assert status.is(201)
}
}
```
But this of course failed because the placeholder always contains just a string and `null` in the data table translates to an empty string. The actual string is also not surrounded by quotes.
I solved it by grabbing the session and extracting the value manually and checking if it was an empty string and then building up my json body to post accordingly, but it was a lot more fuss.
Therefore I am proposing this addition to the DSL. If there is a simpler way to accomplish what I was trying to do, please let me …
> Add WithJsonDataInputs to CoreDSL

- benchmarks/src/main/scala/session/SessionShowBench.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/Session.scala
This PR addresses the first option to mitigate https://github.com/agourlay/cornichon/issues/769
There is a significant gain in allocation by peeling off the `mkString` abstraction.
The two `mkString` calls are flattened into a single `StringBuilder` with minimal overhead.
> Decrease allocations in Session Show

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/dsl/CoreDsl.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/steps/wrapped/EventuallyStep.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/steps/wrapped/EventuallyStepSpec.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/testHelpers/CommonTestSuite.scala
This PR adds a new DSL construct name `EventuallyDiscard` to tackle the issue of large sessions #769 
It is equivalent to `Eventually` but will discard the resulting inner state (session & logs) if one of the wrapped step fails.
> Introduce 'EventuallyDiscard' to discard inner failing states

- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/RunState.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/core/Step.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/dsl/CoreDsl.scala
- cornichon-core/src/main/scala/com/github/agourlay/cornichon/steps/wrapped/WithResourceStep.scala
- cornichon-core/src/test/scala/com/github/agourlay/cornichon/steps/wrapped/WithResourceStepSpec.scala
- cornichon-test-framework/src/test/scala/com/github/agourlay/cornichon/framework/examples/superHeroes/SuperHeroesScenario.scala
Tackles https://github.com/agourlay/cornichon/issues/237
This PR introduces a new abstraction for resource steps which are released at the end of a wrapping scope.
See integration test for example.
> New resource step with explicit scopes
